name: Build and publish the docs machine docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the "master" branch
  push:
    branches: [ "master" ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source
        uses: actions/checkout@v7

      - name: Set up python
        uses: actions/setup-python@v7.0.0

      - name: Set up mkdocs
        run: pip install mkdocs

      - name: Build the docs
        run: mkdocs build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v6.0.0

      - name: Upload built site artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: site/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions: 
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    
    steps:
      - name: Publish to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
